export const itemCards = [
    {
        name: "Mjolnir",
        cost: 500,
        info: "Thor's legendary hammer.",
        rarity: 3,
        image: "/itemimages/thor.jpg",
    },
    {
        name: "Captain America Shield",
        cost: 800,
        info: "Vibranium shield used by Captain America.",
        rarity: 4,
        image: "/itemimages/captain.jpg",
    },
    {
        name: "Iron Man Suit",
        cost: 10000,
        info: "Advanced armor suit used by Tony Stark.",
        rarity: 4,
        image: "/itemimages/ironman.jpg",
    },
    {
        name: "Mjolnir",
        cost: 500,
        info: "Thor's legendary hammer.",
        rarity: 3,
        image: "/itemimages/thor.jpg",
    },
    {
        name: "Captain America Shield",
        cost: 800,
        info: "Vibranium shield used by Captain America.",
        rarity: 4,
        image: "/itemimages/captain.jpg",
    },
    {
        name: "Iron Man Suit",
        cost: 10000,
        info: "Advanced armor suit used by Tony Stark.",
        rarity: 4,
        image: "/itemimages/ironman.jpg",
    },
    {
        name: "Mjolnir",
        cost: 500,
        info: "Thor's legendary hammer.",
        rarity: 3,
        image: "/itemimages/thor.jpg",
    },
    {
        name: "Captain America Shield",
        cost: 800,
        info: "Vibranium shield used by Captain America.",
        rarity: 4,
        image: "/itemimages/captain.jpg",
    },
    {
        name: "Iron Man Suit",
        cost: 10000,
        info: "Advanced armor suit used by Tony Stark.",
        rarity: 4,
        image: "/itemimages/ironman.jpg",
    },
    {
        name: "Mjolnir",
        cost: 500,
        info: "Thor's legendary hammer.",
        rarity: 3,
        image: "/itemimages/thor.jpg",
    },
    {
        name: "Captain America Shield",
        cost: 800,
        info: "Vibranium shield used by Captain America.",
        rarity: 4,
        image: "/itemimages/captain.jpg",
    },
    {
        name: "Iron Man Suit",
        cost: 10000,
        info: "Advanced armor suit used by Tony Stark.",
        rarity: 4,
        image: "/itemimages/ironman.jpg",
    },
];
