export const timelineArr = [
    {
        title: "Red Skull Found Tesseract",
        data: "In the Red Skull Found Tesseract storyline, Johann Schmidt, also known as the Red Skull, discovers the Tesseract, an ancient artifact of immense power. As leader of the Nazi scientific division HYDRA, Schmidt seeks to harness the Tesseract's energy to fuel his ambition for world domination. Unleashing the full potential of the Tesseract, Schmidt plans to create advanced weaponry and turn the tide of World War II in favor of the Axis powers. However, the true nature of the Tesseract and its connection to otherworldly forces prove to be more dangerous than Schmidt could have imagined, setting the stage for cosmic conflict and perilous consequences.",
        image: "/timeline/1rs.webp",
        date: "1942",
    },
    {
        title: "Steve Rogers Turned into Captain America",
        data: "The Steve Rogers Turned into Captain America narrative explores the transformation of a frail young man into the iconic super-soldier and symbol of hope, Captain America. During World War II, Steve Rogers volunteers for a top-secret experiment called Operation Rebirth, which enhances his physical attributes to peak human potential. Injected with the Super-Soldier Serum and exposed to vita-rays, Rogers undergoes a dramatic physical transformation, gaining enhanced strength, agility, and endurance. Embodying the ideals of courage, honor, and selflessness, Captain America emerges as a beacon of heroism and inspiration in the fight against tyranny and injustice.",
        image: "/timeline/2ca.jpg",
        date: "1940s",
    },
    {
        title: "Black Widow Trained in Red Room",
        data: "The Black Widow Trained in Red Room storyline delves into the formative years of Natasha Romanoff, also known as Black Widow, and her training in the infamous Red Room program. Raised as an assassin by the Soviet Union, Natasha undergoes rigorous physical and psychological conditioning to become a lethal operative. The Red Room shapes her into a master spy and combatant, honing her skills in espionage, combat, and manipulation. Natasha's experiences in the Red Room profoundly influence her character and motivations as she navigates the complexities of her past and identity.",
        image: "/timeline/3bw.avif",
        date: "1984",
    },
    {
        title: "Captain Marvel",
        data: "Captain Marvel follows the journey of Carol Danvers, a former U.S. Air Force pilot who becomes the powerful superhero known as Captain Marvel after being exposed to alien technology. Set in the 1990s, the film explores Carol's quest to uncover the truth about her past and her connection to the Kree alien race. Along the way, she teams up with Nick Fury, a young S.H.I.E.L.D. agent, to stop a galactic war between the Kree and their mortal enemies, the shape-shifting Skrulls.",
        image: "/timeline/4cm.jpg",
        date: "2019",
    },
    {
        title: "Iron Man",
        data: "Iron Man follows the transformation of billionaire playboy Tony Stark from arrogant arms dealer to armored superhero. After a near-fatal attack in Afghanistan leaves him critically injured with shrapnel lodged near his heart, Tony is captured by a terrorist group. To escape, he builds a mechanized suit of armor using salvaged materials. This suit not only keeps him alive but also becomes a powerful weapon. As Tony refines his creation, he undergoes a personal transformation. He witnesses the devastating impact of his weapons firsthand and vows to use his technology for good.",
        image: "/timeline/5im.webp",
        date: "2008",
    },
    {
        title: "The Incredible Hulk",
        data: "The Incredible Hulk tells the story of Dr. Bruce Banner, a scientist on the run from the U.S. government. After an experiment goes wrong, Banner is exposed to a massive dose of gamma radiation, which transforms him into the raging green monster known as the Hulk whenever he becomes angry or stressed. Hunted by General Thaddeus Ross and the military, Banner seeks a cure for his condition while trying to evade capture. Along the way, he must confront the consequences of his transformation and the threat posed by a fellow scientist turned villain, Emil Blonsky.",
        image: "/timeline/6hl.webp",
        date: "2008",
    },
    {
        title: "Captain America Thawed from Ice",
        data: "The Captain America Thawed from Ice narrative recounts the remarkable discovery and revival of Steve Rogers, aka Captain America, decades after his presumed death. Frozen in suspended animation since World War II, Rogers is found by S.H.I.E.L.D. agents in the Arctic. Thawed from the ice, Rogers awakens to a world vastly different from the one he left behind, grappling with the passage of time and the loss of his former life. Despite the challenges of acclimating to the modern era, Rogers remains steadfast in his commitment to justice and heroism, resuming his role as the Sentinel of Liberty and a symbol of hope for a new generation.",
        image: "/timeline/7ca.avif",
        date: "2011",
    },
    {
        title: "The Avengers",
        data: "The Avengers brings together Earth's mightiest heroes to battle the extraterrestrial threat posed by Loki, the adopted brother of Thor. Loki seeks to conquer Earth by using the powerful artifact known as the Tesseract, which holds untold energy. To stop him, Nick Fury, director of the espionage agency S.H.I.E.L.D., assembles a team of superheroes, including Iron Man, Captain America, Thor, Hulk, Black Widow, and Hawkeye. Despite their initial conflicts and differences, the Avengers must learn to work together to thwart Loki's plans and prevent a catastrophic invasion.",
        image: "/timeline/8avg.jpg",
        date: "2012",
    },
    {
        title: "Iron Man 3",
        data: "Iron Man 3 sees Tony Stark facing his toughest challenge yet when he comes under attack from a mysterious terrorist known as the Mandarin. As Stark struggles to protect himself and those he cares about, he embarks on a journey of self-discovery and redemption. Haunted by his past mistakes and grappling with anxiety and post-traumatic stress disorder (PTSD), Stark must rely on his intelligence and resourcefulness to confront the Mandarin's forces.",
        image: "/timeline/9im.jpg",
        date: "2013",
    },
    {
        title: "Thor: The Dark World",
        data: "Thor: The Dark World continues the adventures of the Asgardian god of thunder as he battles to save the Nine Realms from a powerful ancient enemy known as Malekith. Malekith, leader of the Dark Elves, seeks to plunge the universe into darkness by harnessing the power of the Aether, a destructive force hidden away for millennia.",
        image: "/timeline/10th.webp",
        date: "2013",
    },
    {
        title: "Captain America: The Winter Soldier",
        data: "Captain America: The Winter Soldier follows Steve Rogers, aka Captain America, as he navigates the complexities of the modern world and faces a new threat from within his own organization, S.H.I.E.L.D. When Rogers discovers that S.H.I.E.L.D. has been compromised by the villainous Hydra, he must unravel a web of conspiracy and corruption that threatens global security.",
        image: "/timeline/11ca.jpg",
        date: "2014",
    },
    {
        title: "Guardians of the Galaxy",
        data: "Guardians of the Galaxy follows a group of intergalactic misfits who come together to protect the universe from the threat of Ronan the Accuser, a powerful alien warlord. Led by Peter Quill, also known as Star-Lord, the Guardians include Gamora, an assassin seeking redemption; Drax the Destroyer, a vengeance-driven warrior; Rocket, a genetically engineered raccoon with a penchant for explosives; and Groot, a sentient tree-like creature with a limited vocabulary.",
        image: "/timeline/12gg.webp",
        date: "2014",
    },
    {
        title: "Guardians of the Galaxy Vol. 2",
        data: "Guardians of the Galaxy Vol. 2 reunites the ragtag team of space-faring heroes as they embark on a new adventure filled with action, humor, and heart. Following their success in the first film, Peter Quill, Gamora, Drax, Rocket, and Groot find themselves pursued by various factions eager to exploit their newfound fame.",
        image: "/timeline/13gg.jpg",
        date: "2017",
    },
    {
        title: "Avengers: Age of Ultron",
        data: "Avengers: Age of Ultron sees Earth's mightiest heroes facing their greatest challenge yet when they encounter Ultron, a sentient artificial intelligence created by Tony Stark and Bruce Banner. Intended as a global peacekeeping force, Ultron instead becomes a genocidal threat determined to eradicate humanity.",
        image: "/timeline/14avg.avif",
        date: "2015",
    },
    {
        title: "Ant-Man",
        data: "Ant-Man tells the story of Scott Lang, a master thief who is recruited by scientist Hank Pym to become the new Ant-Man, a superhero capable of shrinking to the size of an insect while gaining superhuman strength. Lang must embrace his inner hero and learn to work alongside Pym's daughter, Hope van Dyne, as they embark on a daring heist to steal technology from Pym's former protégé, Darren Cross.",
        image: "/timeline/15am.jpg",
        date: "2015",
    },
    {
        title: "Captain America: Civil War",
        data: "Captain America: Civil War pits the Avengers against each other in a divisive conflict over government oversight and accountability. When the United Nations proposes the Sokovia Accords, a set of regulations to govern the activities of superpowered individuals, the team becomes divided.",
        image: "/timeline/16ca.jpg",
        date: "2016",
    },
    {
        title: "Black Widow",
        data: "Black Widow delves into the backstory of Natasha Romanoff, also known as Black Widow, exploring her origins and past missions as a former KGB assassin turned Avenger. Set after the events of Captain America: Civil War, Natasha finds herself on the run from the government and confronts her past as she reunites with her estranged 'family'.",
        image: "/timeline/17bw.avif",
        date: "2021",
    },
    {
        title: "Doctor Strange",
        data: "Doctor Strange follows the journey of Dr. Stephen Strange, a brilliant yet arrogant neurosurgeon whose life is forever changed after a tragic car accident leaves him with severe nerve damage in his hands. Desperate to restore his former abilities, Strange seeks out unconventional healing methods and encounters the Ancient One, a powerful sorcerer.",
        image: "/timeline/18ds.webp",
        date: "2016",
    },
    {
        title: "Spider-Man: Homecoming",
        data: "Spider-Man: Homecoming follows the adventures of Peter Parker, a high school student who juggles his life as a teenager with his responsibilities as the friendly neighborhood Spider-Man. Set in the aftermath of the events of Captain America: Civil War, Peter eagerly awaits his next mission from Tony Stark, aka Iron Man.",
        image: "/timeline/19sm.jpg",
        date: "2017",
    },
    {
        title: "Black Panther",
        data: "Black Panther follows the story of T'Challa, the newly crowned king of the fictional African nation of Wakanda, who also assumes the mantle of the Black Panther, a legendary warrior and protector of his people. As T'Challa grapples with the responsibilities of leadership, he faces internal and external threats to Wakanda's sovereignty.",
        image: "/timeline/20bp.webp",
        date: "2018",
    },
    {
        title: "Ant-Man and The Wasp",
        data: "Ant-Man and The Wasp reunites audiences with Scott Lang, aka Ant-Man, and introduces Hope van Dyne as The Wasp, his partner in heroics. Set after the events of Captain America: Civil War, Scott grapples with the consequences of his choices while under house arrest.",
        image: "/timeline/21am.webp",
        date: "2018",
    },
    {
        title: "Thor: Ragnarok",
        data: "Thor: Ragnarok sees the god of thunder facing his most formidable challenge yet as he confronts the prophesied destruction of his homeland, Asgard, at the hands of the ruthless goddess of death, Hela. Stripped of his iconic hammer, Mjolnir, and exiled to the distant planet of Sakaar, Thor must fight for survival in a deadly gladiatorial contest against his former ally, the Hulk.",
        image: "/timeline/22th.webp",
        date: "2017",
    },
    {
        title: "Avengers: Infinity War",
        data: "Avengers: Infinity War brings together the Avengers and their allies to face off against the formidable cosmic tyrant Thanos, who seeks to acquire all six Infinity Stones and use them to impose his twisted will on the universe. As Thanos' quest for power threatens to destroy half of all life in the universe, the Avengers must put aside their differences and unite to stop him.",
        image: "/timeline/23avg.webp",
        date: "2018",
    },
    {
        title: "Avengers: Endgame",
        data: "Avengers: Endgame follows the aftermath of Avengers: Infinity War as the surviving members of the Avengers and their allies come together for one final mission to undo the devastating effects of Thanos' snap, which wiped out half of all life in the universe. With the help of newly acquired allies and a plan involving time travel, the Avengers embark on a perilous journey through various moments in the past to retrieve the Infinity Stones and restore balance to the universe.",
        image: "/timeline/24avg.jpg",
        date: "2019",
    },
    {
        title: "Spider-Man: Far From Home",
        data: "Spider-Man: Far From Home picks up after the events of Avengers: Endgame as Peter Parker, aka Spider-Man, struggles to come to terms with the loss of his mentor, Tony Stark. Hoping to enjoy a summer vacation with his friends in Europe, Peter's plans are disrupted when he is recruited by Nick Fury to help uncover the mystery behind a series of elemental creature attacks.",
        image: "/timeline/25sm.webp",
        date: "2019",
    },
];
