/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Veysel Gök (https://sketchfab.com/veysel.gok.vg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/captain-america-shield-eb1aee472828453592c370414785bcac
Title: Captain America - Shield
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Shield(props) {
    const { nodes, materials } = useGLTF("/shield/scene.gltf");
    return (
        <group
            {...props}
            dispose={null}
        >
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    geometry={nodes["Cylinder001_Material_#37_0"].geometry}
                    material={materials.Material_37}
                />
                <mesh
                    geometry={nodes["Cylinder001_Material_#25_0"].geometry}
                    material={materials.Material_25}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/shield/scene.gltf");
